#! /usr/bin/python

# autogenerated on 2020-05-20 10:42

# Merge QuadTree 

import cv2
import numpy as np

from utils import *
from lab_14 import split, avg_region_rect
from lab_15 import region_growing, apply_regions

def main():
    img = load_image_from_arg()
    original = np.copy(img)
    tree = split(img, 1, 20, rect=True)
    avg_region_rect(tree)
    regions, count = region_growing(img, 0.025)
    output = apply_regions(img, regions, count)
    show_image(original, img, output, wait=60)

if __name__ == '__main__':
    main()
