#! /usr/bin/python

# autogenerated on 2020-05-14 16:54

# Region Growing

import cv2
import numpy as np
import secrets

from utils import *


def random_seed(regions):
    available = [
        (i, j) for i, row in enumerate(regions) for j, v in enumerate(row) if v == 0
    ]
    if len(available) == 0:
        return None
    else:
        return secrets.choice(available)


def simple_distance(img, center, pixel, _region, _regions):
    x, y = center
    nx, ny = pixel
    return abs(img[x, y] - img[nx, ny]) / (img[x, y] + img[nx, ny] + 1)


def mean_distance(img, _center, pixel, region, regions):
    indexes = np.where(regions == region)
    mean = np.mean(img[indexes], axis=0)
    mean = np.round(mean)
    mean = np.uint8(mean)

    x, y = pixel
    return abs(img[x, y] - mean) / (img[x, y] + mean + 1)


def grow_region(img, regions, pixel, region, seed_list, threshold, borders, distance):
    output = 0
    x, y = pixel
    size_x, size_y = img.shape[0], img.shape[1]
    for i in (-1, 0, 1):
        for j in (-1, 0, 1):    
            nx = x + i
            ny = y + j
            if 0 <= nx < size_x and 0 <= ny < size_y:
                if regions[nx, ny] == 0:
                    if distance(img, (x, y), (nx, ny), region, regions) < threshold:
                        regions[nx, ny] = region
                        seed_list.append((nx, ny))
                        output += 1
                    elif borders:
                        regions[nx, ny] = -1
                        output += 1
    return output


def region_growing(img, threashold, borders=False, simple=True):
    img = img.astype(np.float)
    size_x, size_y = img.shape[0], img.shape[1]
    total = size_y * size_x
    processed = 0
    regions = np.zeros((size_x, size_y), dtype=np.int)

    current = 0
    seed_list = []
    while pixel := random_seed(regions):
        precent = (processed / total) * 100
        print(f"\rComplete {precent:.2f}%", end="")
        current += 1
        seed_list.append(pixel)
        x, y = pixel
        regions[x, y] = current
        processed += 1
        while seed_list:
            pixel = seed_list.pop()
            f = simple_distance if simple else mean_distance
            processed += grow_region(
                img, regions, pixel, current, seed_list, threashold, borders, f
            )

    print()
    return regions, current


def apply_regions(img, regions, total):
    output = np.zeros(img.shape, dtype=np.uint8)
    for i in range(1, total + 1):
        indexes = np.where(regions == i)
        mean = np.mean(img[indexes], axis=0)
        mean = np.round(mean)
        mean = np.uint8(mean)
        output[indexes] = mean
    return output


def main():
    img = load_image_from_arg(color=False)
    regions, current = region_growing(img, 0.01, simple=True)
    print(current, "regions fund")
    segmented = apply_regions(img, regions, current)
    show_image(img, segmented, wait=60)


if __name__ == "__main__":
    main()
