#! /usr/bin/python

# autogenerated on 2020-05-20 11:42

# Morphological Operators

import cv2
import numpy as np

from utils import *


def cross_operator(img, callback):
    size_x, size_y = img.shape
    output = np.zeros((size_x, size_y), dtype=np.uint8)
    for x in range(size_x):
        for y in range(size_y):
            px = max(0, x - 1)
            nx = min(x + 1, size_x - 1)
            py = max(0, y - 1)
            ny = min(y + 1, size_y - 1)
            if callback(img[px, y], img[nx, y], img[x, py], img[x, ny]):
                output[x, y] = 255

    return output

def morphological_operator(img, kernel, value, early):
    size_x, size_y = img.shape
    kx, ky = kernel.shape
    kx //= 2 
    ky //= 2
    output = np.zeros((size_x, size_y), dtype=np.uint8)
    for x in range(size_x):
        for y in range(size_y):
            stat = True
            for i, row in enumerate(kernel):
                if not stat:
                    break
                px = x + (i - kx)
                px = min(max(0, px), size_x-1)
                for j, v in enumerate(row):
                    if v:
                        py = y + (j - ky)
                        py = min(max(0, py), size_y-1)
                        if img[px, py] == 255:
                            if early:
                                output[x, y] = value
                                stat = False
                                break
                        else:
                            stat = False
                            break
            if stat:
                output[x, y] = value
    return output

def erosion(img):
    return cross_operator(img, lambda a, b, c, d: a and b and c and d)


def dilation(img):
    return cross_operator(img, lambda a, b, c, d: a or b or c or d)


def main():
    img = load_image_from_arg()
    _, img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    cross_kernel = np.array(
        [
            [0, 1, 0],
            [1, 0, 1],
            [0, 1, 0]
        ]
    )
    img = 255 - img
    erosion_img = erosion(img)
    dilation_img = dilation(img)

    new_erosion_img = morphological_operator(img, cross_kernel, 255, False)
    new_dilation_img = morphological_operator(img, cross_kernel, 255, True)
    
    show_image(("Binary", img), ("Erosion", erosion_img), ("Dilation", dilation_img), ("New Erosion", new_erosion_img), ("New Dilation", new_dilation_img))


if __name__ == "__main__":
    main()
